### ISSUE TITLE
lxml.etree.XMLSyntaxError: failed to load external entity "NULL", line 1, column 128

### ISSUE THREAD

**Issue by retsyo** [belerico/py_asciimath#12]
I installed py_asciimath, update lxml for my python-3.8.1.amd64 on Windows 10 64 bits
then I try to run the code bellowing, which is actually the code on https://github.com/belerico/py_asciimath, but I get 
```
ASCIIMath to MathML
WARNING:root:No connection available...
WARNING:root:No XML declaration with 'encoding' attribute set: default encoding to None
WARNING:root:The XML encoding is None: default to UTF-8
WARNING:root:No DTD declaration found: set to local mathml2 DTD
Traceback (most recent call last):
  File "a.py", line 12, in <module>
    parsed = asciimath2mathml.translate(
  File "E:\_PRG_BAK\py_asciimath-master\py_asciimath\translator\translator.py", line 336, in translate
    return super(ASCIIMath2MathML, self).translate(
  File "E:\_PRG_BAK\py_asciimath-master\py_asciimath\translator\translator.py", line 136, in translate
    return super(LarkTranslator, self).translate(
  File "E:\_PRG_BAK\py_asciimath-master\py_asciimath\translator\translator.py", line 65, in translate
    exp = self._translate(exp, **kwargs)
  File "E:\_PRG_BAK\py_asciimath-master\py_asciimath\translator\translator.py", line 266, in _translate
    parsed = MathMLParser.parse(
  File "E:\_PRG_BAK\py_asciimath-master\py_asciimath\parser\parser.py", line 297, in parse
    return lxml.etree.fromstring(xml, mathml_parser)
  File "src\lxml\etree.pyx", line 3236, in lxml.etree.fromstring
  File "src\lxml\parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src\lxml\parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src\lxml\parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src\lxml\parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: failed to load external entity "NULL", line 1, column 128

```

the code is 
```python
from py_asciimath.translator.translator import (
    ASCIIMath2MathML,
    ASCIIMath2Tex,
    MathML2Tex,
    Tex2ASCIIMath
)


if __name__ == "__main__":
    print("ASCIIMath to MathML")
    asciimath2mathml = ASCIIMath2MathML(log=False, inplace=True)
    parsed = asciimath2mathml.translate(
        r"e^x > 0 forall x in RR",
        displaystyle=True,
        dtd="mathml2",
        dtd_validation=True,
        from_file=False,
        output="string",
        network=True,
        pprint=False,
        to_file=None,
        xml_declaration=True,
        xml_pprint=True,
    )

    print(parsed, "\n\nMathML to LaTeX")
    mathml2tex = MathML2Tex()
    parsed = mathml2tex.translate(parsed, network=False, from_file=False,)

    print(parsed, "\n\nASCIIMath to LaTeX")
    asciimath2tex = ASCIIMath2Tex(log=False, inplace=True)
    parsed = asciimath2tex.translate(
        r"e^x > 0 forall x in RR",
        displaystyle=True,
        from_file=False,
        pprint=False,
    )

    print(parsed, "\n\nLaTeX to ASCIIMath")
    tex2asciimath = Tex2ASCIIMath(log=False, inplace=True)
    parsed = tex2asciimath.translate(
        parsed,
        from_file=False,
        pprint=False,
    )
    print(parsed)
```

**Comment by belerico** [comment]
Hi @retsyo, sorry for the late response. I think it is only a Windows problem, which it was not in my plans to be supported, but i can work also on a windows implementation. Do you mind to open a PR if you have already something working?
BTW, on Linux this is the output that i've obtained running your code:

```bash
ASCIIMath to MathML
WARNING:root:No XML declaration with 'encoding' attribute set: default encoding to None
WARNING:root:The XML encoding is None: default to UTF-8
WARNING:root:No DTD declaration found: set to remote mathml2 DTD
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE math PUBLIC "-//W3C//DTD MathML 2.0//EN" "http://www.w3.org/Math/DTD/mathml2/mathml2.dtd">
<math xmlns="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink">
  <mstyle displaystyle="true">
    <mrow>
      <msup>
        <mrow>
          <mi>e</mi>
        </mrow>
        <mrow>
          <mi>x</mi>
        </mrow>
      </msup>
    </mrow>
    <mo>&gt;</mo>
    <mn>0</mn>
    <mo>&ForAll;</mo>
    <mi>x</mi>
    <mo>&in;</mo>
    <mo>&Ropf;</mo>
  </mstyle>
</math>
 

MathML to LaTeX
WARNING:root:Remote DTD found and network is False: replacing with local DTD
$ {\displaystyle {e}^{x}>0\forall x\in \mathbb{R} }$ 

ASCIIMath to LaTeX
\[{e}^{x} > 0 \forall x \in \mathbb{R}\] 

LaTeX to ASCIIMath
(e)^(x) > 0 AA x in RR
```

**Comment by EndlessXYZ** [comment]
@retsyo  @belerico 

I met the same problem on Win 10, and found it's because the inconsistency of delimiters of path on different systems.

Quick fix:  (in `__init__.py`)
```python
import os
import platform

if (platform.system() == 'Windows'):
    PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__)).replace('\\', '/')
else:
    PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))

__version__ = "0.3.0"
```

**Comment by retsyo** [comment]
Nice, it solved the problem. Thanks.

**Comment by martiniifun** [comment]
Could you please attach this solution on your main branch, please?
I'm developing a Korean WordProcessor(HWP, for windows OS) parsing tool and
py-asciimath module helps me a lot!

Just for me, it's okay. (I already modified `__init__.py`)
but, my collegues can't handle that..

**Comment by malmsteen** [comment]
> [@retsyo](https://github.com/retsyo) [@belerico](https://github.com/belerico)
 It did. Thank you!

**Comment by malmsteen** [comment]
@EndlessXYZ 
It helped, thank you! Avoided moving project to WSL
